import { athleteStats } from '@/data/athleteStats';
import { clubStats, ClubStats } from '@/data/clubStats';
import { AthleteStats } from '@/data/types';
import styles from '@/styles/Home.module.css';
import { orderBy } from 'lodash';
import Head from 'next/head';
import Link from 'next/link';

function TopAthletes({
    title,
    getStat,
}: {
    title: string;
    getStat: (data: AthleteStats) => number;
}) {
    const topN = orderBy(athleteStats, getStat, 'desc').slice(0, 10);
    return (
        <div className={styles.topList}>
            <h3>{title}</h3>
            <ol>
                {topN.map((athlete) => (
                    <li key={athlete.slug}>
                        <Link href={`/athlete/${athlete.slug}`}>
                            {athlete.name} - {getStat(athlete)}
                        </Link>
                    </li>
                ))}
            </ol>
        </div>
    );
}

function TopClubs({
    title,
    getStat,
}: {
    title: string;
    getStat: (data: ClubStats) => number;
}) {
    const topN = orderBy(clubStats, getStat, 'desc').slice(0, 10);
    return (
        <div className={styles.topList}>
            <h3>{title}</h3>
            <ol>
                {topN.map((club) => (
                    <li key={club.slug}>
                        <Link href={`/club/${club.slug}`}>
                            {club.name} - {getStat(club)}
                        </Link>
                    </li>
                ))}
            </ol>
        </div>
    );
}

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.container}>
                <div className={styles.topGrid}>
                    <TopAthletes
                        title="Most Total Years on Team"
                        getStat={(a) => a.total.yearCount}
                    />
                    <TopAthletes
                        title="Most Years on Senior Team"
                        getStat={(a) => a.senior?.yearCount || 0}
                    />
                    <TopAthletes
                        title="Most Years on Junior Team"
                        getStat={(a) => a.junior?.yearCount || 0}
                    />
                    <TopAthletes
                        title="Most Consecutive Years on Team"
                        getStat={(a) => a.total.longestStreak?.yearCount || 0}
                    />
                    <TopAthletes
                        title="Longest Career Span"
                        getStat={(a) => 1 + a.total.end - a.total.start}
                    />
                    <TopAthletes
                        title="Child Prodigies"
                        getStat={(a) =>
                            (a.junior?.yearCount || 0) -
                            (a.senior?.yearCount || 0)
                        }
                    />
                </div>
                <hr />
                <div className={styles.topGrid}>
                    <TopClubs
                        title="Most Athlete-Years"
                        getStat={(c) => c.totalAthleteYears}
                    />
                    <TopClubs
                        title="Most Years Represented"
                        getStat={(c) => c.yearsRepresented}
                    />
                    <TopClubs
                        title="Most Athletes"
                        getStat={(c) => c.countDistinctAthletes}
                    />
                    <TopClubs
                        title="Highest Average Years Per Athlete"
                        getStat={(c) => c.avgYearsPerAthlete}
                    />
                    <TopClubs
                        title="Most Athletes at Once"
                        getStat={(c) => c.mostConcurrentAthletes}
                    />
                </div>
            </main>
        </>
    );
}
